"use client";

import { useCallback, useEffect, useState } from "react";
import GlassCard from "@/components/ui/GlassCard";
import Button from "@/components/ui/Button";
import Icon from "@/components/ui/Icons";
import { supabase } from "@/lib/supabaseClient";
import { haptic } from "@/lib/haptics";

type AIState =
  | { status: "loading" }
  | { status: "ready"; insights: string; provider: string; model: string }
  | { status: "unavailable"; message: string };

/**
 * Server-generated AI insights. The server aggregates the month's transactions
 * into a privacy-filtered summary and asks the configured provider for a
 * plain-language overview. This card is purely presentational and degrades
 * gracefully (loading → unavailable) when AI is disabled or unreachable.
 */
export default function AIInsights() {
  const [state, setState] = useState<AIState>({ status: "loading" });

  const load = useCallback(async () => {
    setState({ status: "loading" });
    try {
      const { data } = await supabase.auth.getSession();
      const token = data.session?.access_token;
      if (!token) {
        setState({ status: "unavailable", message: "Sign in to see AI insights." });
        return;
      }

      const res = await fetch("/api/v1/ai/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({}),
      });
      const body = (await res.json().catch(() => ({}))) as {
        available?: boolean;
        insights?: string;
        provider?: string;
        model?: string;
        message?: string;
      };

      if (res.status === 429) {
        setState({
          status: "unavailable",
          message: body.message ?? "Too many requests. Please try again in a minute.",
        });
        return;
      }
      if (!res.ok) {
        setState({ status: "unavailable", message: "AI insights are unavailable right now. Try again in a moment." });
        return;
      }
      if (body.available && body.insights) {
        setState({
          status: "ready",
          insights: body.insights,
          provider: body.provider ?? "ai provider",
          model: body.model ?? "",
        });
      } else {
        setState({
          status: "unavailable",
          message: body.message ?? "AI insights are currently unavailable.",
        });
      }
    } catch {
      setState({
        status: "unavailable",
        message: "Could not reach the insights service. Check your connection and try again.",
      });
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  return (
    <GlassCard className="p-5" hover>
      <div className="flex items-start gap-4">
        <span className="h-11 w-11 rounded-2xl inline-flex items-center justify-center shrink-0" style={{ background: "#a855f71a", color: "#a855f7" }}>
          <Icon name="sparkles" size={22} />
        </span>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-3">
            <h3 className="font-semibold text-snow">FinSight AI</h3>
            <span className="text-[11px] uppercase tracking-wide px-2 py-0.5 rounded-full" style={{ background: "#a855f722", color: "#c084fc" }}>
              Server
            </span>
          </div>
          <p className="text-sm text-slate">
            A plain-language overview of this month, written by an external AI model.
          </p>
        </div>
        <Button variant="default" icon="refresh" onClick={() => { haptic("success"); load(); }} disabled={state.status === "loading"} className="shrink-0">
          <span className="hidden sm:inline">Refresh</span>
        </Button>
      </div>

      <div className="mt-4">
        {state.status === "loading" && (
          <div className="space-y-2.5">
            <div className="h-4 w-full rounded-full bg-tint animate-pulse" />
            <div className="h-4 w-4/5 rounded-full bg-tint animate-pulse" />
            <div className="h-4 w-3/5 rounded-full bg-tint animate-pulse" />
          </div>
        )}

        {state.status === "unavailable" && (
          <div className="flex items-start gap-3 rounded-2xl p-4" style={{ background: "#94a3b822", boxShadow: "inset 0 0 0 1px #94a3b833" }}>
            <Icon name="info" size={18} className="text-slate mt-0.5" />
            <p className="text-sm text-slate leading-relaxed">{state.message}</p>
          </div>
        )}

        {state.status === "ready" && (
          <div className="rounded-2xl p-4 text-sm leading-relaxed text-snow" style={{ background: "#a855f70f", boxShadow: "inset 0 0 0 1px #a855f733" }}>
            <p className="whitespace-pre-line">{state.insights}</p>
            <p className="text-[12px] text-slate mt-3 pt-3" style={{ borderTop: "1px solid #ffffff12" }}>
              Generated by {state.provider}
              {state.model ? ` (${state.model})` : ""}. Only your month&apos;s totals and category names were shared —
              never your notes or individual transactions.
            </p>
          </div>
        )}
      </div>
    </GlassCard>
  );
}
